%data=load('/Users/dongzeyuan1/Desktop/data.mat');
X=rand(28,28,28,1,12);
label={'0','2','3','5','6','9','8','7','5','4','2','1'};
Y=categorical(label);
layers = [
    image3dInputLayer([28 28 28 1])
    convolution3dLayer(5,16,'Stride',4)
    reluLayer
    maxPooling3dLayer(2,'Stride',4)
    fullyConnectedLayer(10)
    softmaxLayer
    classificationLayer];
options=trainingOptions('sgdm', ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropFactor',0.2, ...
    'LearnRateDropPeriod',5, ...
    'MaxEpochs',5000, ...
    'Shuffle','every-epoch', ...
    'MiniBatchSize',64, ...
    'Plots','training-progress');
net1=trainNetwork(X,Y,layers,options);
save('model1','net1')